name: Run code checks

on:
  # Trigger code checks on opening or updating a pull request.
  pull_request:

  # Pushing to the master branch triggers code checks.
  push:
    branches:
      - master
    tags-ignore:
      - "**" # Ignore all tags to prevent duplicate checks when tags are pushed.

  # It should also be possible to trigger checks manually.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actions_lint_check:
    name: Actions lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.12

  spell_check:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check spelling with typos
        uses: crate-ci/typos@v1

  lint_check:
    name: Lint check
    uses: apify/workflows/.github/workflows/python_lint_check.yaml@v0.45.0
    with:
      python_versions: '["3.14"]'

  type_check:
    name: Type check
    uses: apify/workflows/.github/workflows/python_type_check.yaml@v0.45.0
    with:
      python_versions: '["3.14"]'
