name: Code quality checks

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint_and_type_checks:
    name: Run lint and type checks
    uses: ./.github/workflows/lint_and_type_checks.yaml
